# Automatically generated by Pynguin.
import src.container_water as module_0


def test_case_0():
    list_0 = []
    solution_0 = module_0.Solution()
    int_0 = solution_0.maxArea(list_0)
    assert int_0 == -1
    assert solution_0 is not None
    solution_1 = module_0.Solution()
    assert solution_1 is not None


def test_case_1():
    list_0 = []
    solution_0 = module_0.Solution(*list_0)
