# Automatically generated by Pynguin.
import src.two_sum as module_0


def test_case_0():
    solution_0 = module_0.Solution()
    int_0 = -2700
    int_1 = 4811
    list_0 = [int_1, int_0, int_1, int_0]
    list_1 = solution_0.twoSum(list_0, int_0)
    assert solution_0 is not None
    assert list_1 is None


def test_case_1():
    list_0 = []
    int_0 = 1437
    solution_0 = module_0.Solution()
    list_1 = solution_0.twoSum(list_0, int_0)
    assert solution_0 is not None
    assert list_1 is None


def test_case_2():
    int_0 = 11
    int_1 = 1817
    list_0 = [int_0, int_0, int_1, int_0]
    int_2 = 3193
    solution_0 = module_0.Solution()
    list_1 = solution_0.twoSum(list_0, int_2)
    assert solution_0 is not None
    assert list_1 is None
